[package]
name = "img-bri-groups"
version = "0.3.0"
authors = ["Ivan I. Grushin <iigrushin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quicli = "~0.4"
structopt = "~0.2"
image = "~0.24"
